<a href="https://colab.research.google.com/github/ushasri0412/Data-Science-Task/blob/main/numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TASK**

#1. CREATE ARRAYS

#2. ARRAY DIMENSIONS


In [ ]:
# PRINT dimensions of both the arrays
res1=arr_1.ndim
res2=arr_2.ndim
res3=arr_3.ndim
print(res1,res2,res3)

1 1 2


In [ ]:
# PRINT shape of both the arrays
res4=arr_1.shape
res5=arr_2.shape
res6=arr_3.shape
print(res4,res5,res6)

(10,) (9,) (3, 3)


In [ ]:

# 1D array of 10 equally spaced values between 0 and 50
arr_1= np.linspace(0,51,10)
arr_1

array([ 0.        ,  5.66666667, 11.33333333, 17.        , 22.66666667,
       28.33333333, 34.        , 39.66666667, 45.33333333, 51.        ])

In [ ]:
# 2D array of shape (3*3) containing random integers between 5 and 20
import random
arr_2=np.random.randint(5,21,9)
arr_3=arr_2.reshape(3,3)
print(arr_3)

[[13 10  6]
 [16 20  8]
 [ 7 11  6]]


#3 Reshaping

In [ ]:
#  reshape 2d array to 1d
arr_4=arr_3.reshape(9,)
print(arr_4)


[13 10  6 16 20  8  7 11  6]


In [ ]:
#again reshape to 2d
arr_5=arr_4.reshape(3,3)
print(arr_5)

[[13 10  6]
 [16 20  8]
 [ 7 11  6]]


# 4. Indexing

In [ ]:
# for the 2d array created in part 1 , print element in 2nd row and 3rd col
ele=arr_5[1,2]
print(ele)

8


# 5. Slicing

In [ ]:
#extract first 2 rows and last 2 columns of array
op1=arr_5[0:2,1:]
print(op1)

[[10  6]
 [20  8]]


In [ ]:
# slice the first 4 elements from the flattened 1D array
arr_6=arr_5.reshape(-1)
op2=arr_6[4:]
print(op2)

[20  8  7 11  6]


# 6. Array Arithemetic


In [ ]:
# create another 1d array of 10 integers between 1 and 10
arr_7=np.arange(1,10)
arr_7

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# perform the following element wise operations between the 1D arrays created in part 1 and part 3
#addition
# subtraction
# multiplication
op3=arr_4+arr_7
print(op3)
op4=arr_4 - arr_7
print(op4)
op5=arr_4 * arr_7
print(op5)

[14 12  9 20 25 14 14 19 15]
[12  8  3 12 15  2  0  3 -3]
[ 13  20  18  64 100  48  49  88  54]


# 7.Random Numbers


In [ ]:
#  create a 1D array of 5 random values between 0 and 1
np.random.rand(5)

array([0.81577904, 0.11954084, 0.34202817, 0.33138718, 0.58067872])

In [ ]:
# create another 1D array of 5 random values between -1 and 1
np.random.randint(-1,1,5)

array([ 0,  0,  0, -1,  0])

# 8. Challenge Task

In [ ]:
# write a program that asks the user to input a number(n) and then generates as n*n array of random integers between 1 and 100
n=int(input())
arr_8=np.random.randint(1,100,n*n)
arr_9=arr_8.reshape(n,n)
print(arr_9)

3
[[87 61 21]
 [81 93 95]
 [ 2 93 20]]


In [ ]:
#find the sum of all the elements in the array and print the result
op6=np.sum(arr_9)
print(op6)

553
